// UI strings of the quiz engine (student page + teacher console), KZ/RU.
// Kept next to the engine instead of the site-wide strings.ts: these labels
// only exist inside /play and the embedded console.

import type { PackLang } from "./pack";

export const ENGINE_STRINGS = {
  kz: {
    // student — join
    join_title: "Тестке қосылу",
    join_name_label: "Атың",
    join_name_placeholder: "Аты-жөніңді жаз",
    join_code_label: "Бөлме коды",
    join_code_placeholder: "Мысалы: A1B2C3",
    join_button: "Қосылу",
    join_pending: "Қосылуда...",
    err_name: "Атыңды жаз.",
    err_code: "Бөлме кодын жаз.",
    err_not_found: "Бұндай бөлме табылмады. Кодты тексер.",
    err_ended: "Бұл сабақ аяқталып қойды.",
    err_network: "Байланыс қатесі. Қайталап көр.",
    // student — waiting
    waiting_title: "Мұғалімді күтеміз...",
    waiting_desc: "Тест мұғалім бастаған кезде ашылады.",
    waiting_you: "Сен қосылдың",
    // student — quiz
    question_label: "Сұрақ",
    check_button: "Тексеру",
    next_button: "Келесі",
    finish_button: "Аяқтау",
    input_placeholder: "Жауабыңды осында жаз",
    feedback_correct: "Дұрыс! 🎉",
    feedback_wrong: "Қате",
    correct_answer_label: "Дұрыс жауап",
    solution_label: "Шешуі",
    formulas_button: "Формулалар",
    figure_button: "Сызба",
    hint_button: "Кеңес",
    hint_next: "Келесі кеңес",
    calc_button: "Калькулятор",
    score_label: "Ұпай",
    streak_label: "Қатарынан",
    // student — done / ended
    done_title: "Барлық сұрақ аяқталды! 🏁",
    done_desc: "Нәтижең мұғалімнің экранында. Сабақ аяқталғанша күте тұр.",
    ended_title: "Сабақ аяқталды",
    ended_desc: "Мұғалім тестті аяқтады. Жарайсың!",
    kicked_title: "Мұғалім сені тесттен шығарды",
    kicked_desc: "Егер бұл қателік болса — қайта қосыла аласың.",
    kicked_rejoin: "Қайта қосылу",
    result_label: "Нәтижең",
    close_button: "Жабу",
    preview_badge: "АЛДЫН АЛА ҚАРАУ",
    preview_show_answers: "Жауаптарды көрсету",
    preview_hide_answers: "Жауаптарды жасыру",
    // console — setup
    c_questions: "сұрақ",
    c_open_room: "Бөлме ашу",
    c_creating: "Ашылуда...",
    c_err_unauthorized: "Бөлме ашу үшін жүйеге кіру қажет.",
    c_err_network: "Серверге қосылу мүмкін болмады. Қайталап көріңіз.",
    // console — resume an open room after a reload/closed tab
    c_resume_title: "Ашық бөлме табылды",
    c_resume_desc:
      "Бөлме әлі жұмыс істеп тұр — қайта қосылсаңыз, оқушылар нәтижелерімен оралады.",
    c_resume_desc_ended:
      "Тест аяқталды, бірақ нәтижелері сақтаулы — ашуға болады.",
    c_resume_button: "Қайта қосылу",
    c_resume_results: "Нәтижелерді ашу",
    c_resume_discard: "Жаңасын бастау",
    c_resume_discard_confirm:
      "Ашық бөлме жабылады — оқушыларға «тест аяқталды» деп көрсетіледі. Жаңасын бастайсыз ба?",
    // console — question picker
    c_select_hint: "Тестке кіретін сұрақтарды таңдаңыз",
    c_select_all: "Барлығын таңдау",
    c_deselect_all: "Таңдауды алу",
    c_selected: "таңдалды",
    c_none_selected: "Кемінде бір сұрақ таңдаңыз.",
    // console — generator setup (teacher ticks sections + question types)
    c_gen_sections: "Бөлімдер",
    c_gen_sections_hint: "Қандай функция түрлерінен сұрақ құрылады",
    c_gen_modes: "Сұрақ түрлері",
    c_gen_modes_hint: "Таңдалғандары кезектесіп, аралас келеді",
    c_gen_pick: "Кемінде бір бөлім және бір сұрақ түрін таңдаңыз.",
    c_gen_endless: "Шексіз сұрақтар — автоматты құрылады",
    g_mode_A: "Формула → график",
    g_mode_B: "График → қасиет",
    g_mode_C: "График → формула",
    g_mode_D: "Теңдеу → сызу",
    // console — order mode
    c_mode_custom: "Менің ретім",
    c_mode_custom_desc: "Сұрақтар сіз құрған ретпен беріледі",
    c_mode_shuffle: "Кездейсоқ рет",
    c_mode_shuffle_desc: "Әр оқушыға сұрақтар мен нұсқалар өз ретімен араласады",
    // console — student aids (what the student's screen offers this room)
    c_features_title: "Оқушыға көмек",
    c_features_hint: "Тест кезінде оқушы экранында не болады",
    c_feat_figure: "Сызба",
    c_feat_theory: "Формулалар",
    c_feat_hints: "Кеңестер",
    c_feat_calc: "Калькулятор",
    // console — selection tray
    c_tray_title: "Таңдалған сұрақтар",
    c_tray_shuffle_note: "Реті маңызды емес — әр оқушыға өз кездейсоқ реті түседі",
    c_move_up: "Жоғары",
    c_move_down: "Төмен",
    c_remove_question: "Алып тастау",
    // console — tag filters
    c_filter_all: "Барлығы",
    // console — saved quizzes
    c_save_quiz: "Тестті сақтау",
    c_save_changes: "Өзгерістерді сақтау",
    c_save_as_new: "Жаңа тест ретінде сақтау",
    c_save_name_placeholder: "Мысалы: 8Б — бақылау жұмысы",
    c_save_confirm: "Сақтау",
    c_save_cancel: "Болдырмау",
    c_saved_ok: "Сақталды",
    c_saved_hint: "Сақталған тесттер профиліңізде тұрады",
    c_save_err: "Сақтау мүмкін болмады. Қайталап көріңіз.",
    c_save_err_limit: "Сақталған тесттер шегіне жеттіңіз. Профильде ескілерін өшіріңіз.",
    c_saved_missing: "{n} сұрақ жинақта енді жоқ — тізімнен алынды. Сақтасаңыз, тест осы күйде жаңарады.",
    // console — lobby
    c_room_code: "Бөлме коды",
    c_scan_hint: "Оқушылар QR-кодты сканерлейді немесе мына сайтқа кіреді:",
    c_join_host: "join.matem.school",
    c_students: "Оқушылар",
    c_waiting_students: "Оқушылардың қосылуын күтеміз...",
    c_start: "Тестті бастау",
    c_back: "Артқа",
    c_show_qr: "QR үлкейту",
    c_copy_link: "Сілтемені көшіру",
    c_copied: "Көшірілді!",
    // console — one live room per teacher
    c_conflict_confirm:
      "Сізде ашық тест бар: «{title}» (коды {code}). Оны аяқтап, жаңасын бастайсыз ба?",
    // console — remove a student
    c_kick: "Оқушыны шығару",
    c_kick_confirm: "{name} тесттен шығарылсын ба?",
    // console — live
    c_end: "Аяқтау",
    c_end_confirm: "Тестті аяқтайсыз ба?",
    c_no_students: "Әзірге ешкім қосылған жоқ.",
    c_finished_tag: "аяқтады",
    c_away_tag: "шығып кетті",
    c_answers_label: "жауап",
    c_fullscreen: "Толық экран",
    c_stat_correct: "Дұрыс",
    c_stat_wrong: "Қате",
    c_stat_total: "Барлығы",
    c_on_screen: "Экранда",
    c_off_screen: "Сыртта",
    c_out_count: "сыртта",
    // console — results
    c_results_title: "Нәтижелер",
    c_new_session: "Жаңа сессия",
    c_results_empty: "Бұл сессияда оқушы болмады.",
    c_results_note: "Нәтижелер сақталмайды — экранды жаппас бұрын қажетін жазып алыңыз.",
    c_results_saving: "Нәтижелер профильге сақталуда…",
    c_results_saved: "Нәтижелер профиліңізге сақталды.",
    c_results_save_error: "Нәтижелерді сақтау сәтсіз болды.",
    c_results_retry: "Қайталау",
  },
  ru: {
    // student — join
    join_title: "Подключение к тесту",
    join_name_label: "Твоё имя",
    join_name_placeholder: "Напиши имя и фамилию",
    join_code_label: "Код комнаты",
    join_code_placeholder: "Например: A1B2C3",
    join_button: "Подключиться",
    join_pending: "Подключение...",
    err_name: "Напиши своё имя.",
    err_code: "Введи код комнаты.",
    err_not_found: "Такая комната не найдена. Проверь код.",
    err_ended: "Этот урок уже завершён.",
    err_network: "Ошибка связи. Попробуй ещё раз.",
    // student — waiting
    waiting_title: "Ждём учителя...",
    waiting_desc: "Тест откроется, когда учитель его запустит.",
    waiting_you: "Ты подключен",
    // student — quiz
    question_label: "Вопрос",
    check_button: "Проверить",
    next_button: "Дальше",
    finish_button: "Завершить",
    input_placeholder: "Напиши ответ здесь",
    feedback_correct: "Верно! 🎉",
    feedback_wrong: "Неверно",
    correct_answer_label: "Правильный ответ",
    solution_label: "Решение",
    formulas_button: "Формулы",
    figure_button: "Чертёж",
    hint_button: "Подсказка",
    hint_next: "Следующая подсказка",
    calc_button: "Калькулятор",
    score_label: "Баллы",
    streak_label: "Подряд",
    // student — done / ended
    done_title: "Все вопросы пройдены! 🏁",
    done_desc: "Твой результат на экране учителя. Подожди окончания урока.",
    ended_title: "Урок завершён",
    ended_desc: "Учитель завершил тест. Молодец!",
    kicked_title: "Учитель удалил тебя из теста",
    kicked_desc: "Если это ошибка — можно присоединиться снова.",
    kicked_rejoin: "Присоединиться снова",
    result_label: "Твой результат",
    close_button: "Закрыть",
    preview_badge: "ПРЕДПРОСМОТР",
    preview_show_answers: "Показать ответы",
    preview_hide_answers: "Скрыть ответы",
    // console — setup
    c_questions: "вопросов",
    c_open_room: "Открыть комнату",
    c_creating: "Открываем...",
    c_err_unauthorized: "Чтобы открыть комнату, войдите в систему.",
    c_err_network: "Не удалось связаться с сервером. Попробуйте ещё раз.",
    // console — resume an open room after a reload/closed tab
    c_resume_title: "Найдена открытая комната",
    c_resume_desc:
      "Комната ещё работает — переподключитесь, и ученики вернутся на экран со своими результатами.",
    c_resume_desc_ended:
      "Тест уже завершился, но результаты целы — их можно открыть.",
    c_resume_button: "Переподключиться",
    c_resume_results: "Открыть результаты",
    c_resume_discard: "Начать заново",
    c_resume_discard_confirm:
      "Открытая комната будет закрыта — ученики увидят «урок завершён». Начать заново?",
    // console — question picker
    c_select_hint: "Выберите вопросы, которые войдут в тест",
    c_select_all: "Выбрать все",
    c_deselect_all: "Снять все",
    c_selected: "выбрано",
    c_none_selected: "Выберите хотя бы один вопрос.",
    // console — generator setup (teacher ticks sections + question types)
    c_gen_sections: "Разделы",
    c_gen_sections_hint: "Из каких видов функций создавать вопросы",
    c_gen_modes: "Типы вопросов",
    c_gen_modes_hint: "Выбранные будут чередоваться вперемешку",
    c_gen_pick: "Выберите хотя бы один раздел и один тип вопросов.",
    c_gen_endless: "Бесконечные вопросы — создаются автоматически",
    g_mode_A: "Формула → график",
    g_mode_B: "График → свойство",
    g_mode_C: "График → формула",
    g_mode_D: "Уравнение → построить",
    // console — order mode
    c_mode_custom: "Мой порядок",
    c_mode_custom_desc: "Вопросы идут в порядке, который вы задали",
    c_mode_shuffle: "Случайный порядок",
    c_mode_shuffle_desc: "У каждого ученика свой порядок вопросов и вариантов",
    // console — student aids (what the student's screen offers this room)
    c_features_title: "Помощь ученику",
    c_features_hint: "Что будет на экране ученика во время теста",
    c_feat_figure: "Чертёж",
    c_feat_theory: "Формулы",
    c_feat_hints: "Подсказки",
    c_feat_calc: "Калькулятор",
    // console — selection tray
    c_tray_title: "Выбранные вопросы",
    c_tray_shuffle_note: "Порядок не важен — у каждого ученика он свой",
    c_move_up: "Вверх",
    c_move_down: "Вниз",
    c_remove_question: "Убрать",
    // console — tag filters
    c_filter_all: "Все",
    // console — saved quizzes
    c_save_quiz: "Сохранить тест",
    c_save_changes: "Сохранить изменения",
    c_save_as_new: "Сохранить как новый",
    c_save_name_placeholder: "Например: 8Б — контрольная",
    c_save_confirm: "Сохранить",
    c_save_cancel: "Отмена",
    c_saved_ok: "Сохранено",
    c_saved_hint: "Сохранённые тесты лежат в вашем профиле",
    c_save_err: "Не удалось сохранить. Попробуйте ещё раз.",
    c_save_err_limit: "Достигнут лимит сохранённых тестов. Удалите старые в профиле.",
    c_saved_missing: "{n} вопрос(а/ов) больше нет в наборе — они убраны из списка. При сохранении тест обновится.",
    // console — lobby
    c_room_code: "Код комнаты",
    c_scan_hint: "Ученики сканируют QR-код или заходят на сайт:",
    c_join_host: "join.matem.school",
    c_students: "Ученики",
    c_waiting_students: "Ждём подключения учеников...",
    c_start: "Начать тест",
    c_back: "Назад",
    c_show_qr: "Увеличить QR",
    c_copy_link: "Скопировать ссылку",
    c_copied: "Скопировано!",
    // console — one live room per teacher
    c_conflict_confirm:
      "У вас уже открыт тест «{title}» (код {code}). Завершить его и начать новый?",
    // console — remove a student
    c_kick: "Убрать ученика",
    c_kick_confirm: "Убрать {name} из теста?",
    // console — live
    c_end: "Завершить",
    c_end_confirm: "Завершить тест?",
    c_no_students: "Пока никто не подключился.",
    c_finished_tag: "закончил",
    c_away_tag: "вышел",
    c_answers_label: "отв.",
    c_fullscreen: "Во весь экран",
    c_stat_correct: "Верно",
    c_stat_wrong: "Ошибки",
    c_stat_total: "Всего",
    c_on_screen: "На экране",
    c_off_screen: "Вне экрана",
    c_out_count: "вне экрана",
    // console — results
    c_results_title: "Результаты",
    c_new_session: "Новая сессия",
    c_results_empty: "В этой сессии не было учеников.",
    c_results_note: "Результаты не сохраняются — запишите нужное до закрытия экрана.",
    c_results_saving: "Результаты сохраняются в профиль…",
    c_results_saved: "Результаты сохранены в вашем профиле.",
    c_results_save_error: "Не удалось сохранить результаты.",
    c_results_retry: "Повторить",
  },
} as const;

export type EngineStringKey = keyof (typeof ENGINE_STRINGS)["kz"];

export function engineT(lang: PackLang) {
  return (key: EngineStringKey): string => ENGINE_STRINGS[lang][key];
}
